config/routes.rb
Rails.application.routes.draw do
  

 resources :cuisines


get "signin" => "sessions#new"
get "signup" => "users#new"

resource :session

resources :users
  root "places#index"

get "places/filter/:scope" => "places#index", as: :filter
get "user/reviews" => "users#user_reviews", as: :user_reviews
  resources :places do
    resources :reviews
    resources :check_ins
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, length: { minimum: 6, allow_blank: true }
  validates :name, presence: true
  validates :email, presence: true, format:/\A\S+@\S+\z/,
  									uniqueness: { case_sensitive: false}
  has_many :reviews, dependent: :destroy
  has_many :check_ins, dependent: :destroy
  has_many :visited_places, through: :check_ins, source: :place
def gravatar_id                   
  Digest::MD5::hexdigest(email.downcase)
end

def self.authenticate(email, password)
	user = User.find_by(email: email)
	 user && user.authenticate(password)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_signin, except: [:new, :create]
	before_action :require_correct_user, only: [:edit, :update, :destroy]
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@reviews = @user.reviews
		@visited_places = @user.visited_places
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user, notice: "Thanks for signing up!"
		else 
			render :new
		end
	end

	def edit
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user, notice: "Account successfully updated."
		else
			render :edit
		end
	end
	def destroy
  		@user.destroy
  		session[:user_id] = nil
  		redirect_to root_url, alert: "Account successfully deleted!"
	end


private
	def user_params 
	params.require(:user).permit(:name,:email, :password, :password_confirmation)
	end
	def require_correct_user
		@user = User.find(params[:id])
		unless current_user?(@user)
			redirect_to root_url
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
def profile_image_for(user, options={})
  size = options[:size] || 80
  url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}?s=#{size}"
  image_tag(url, alt: user.name)
end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

	<%= render 'shared/errors', object: @user %>

	<p>
		
		<%= f.label :name %>

		<%= f.text_field :name %>

	</p>
	<p> 
		<%= f.label :email %><br/>

		<%= f.text_field :email %>

	</p>
	<p>
		<%= f.label :password %></br>

		<%= f.password_field :password %>

	</p>
	<p>
		<%= f.label :password_confirmation %></br>
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<% if @user.new_record? %>
		<%= f.submit %>
		<% else %>
		<%= f.submit "Update Account" %>
		<% end %>
	<% end %>
</p>
	<p>
<%= link_to "Back to Restaurants","/places" %>
</p>

app/views/users/edit.html.erb
 <% content_for(:title, "Update Account") %>
<h1>Update Account</h1><p>
<%= render 'form' %>
</p>

app/views/users/index.html.erb
 <% content_for(:title, "All Users") %>
<header id="content header">
	<h1><%= pluralize(@users.size, 'User') %></h1>
	<header>
		<ul id="users">
			<% @users.each do |user| %>
			<li> <%= link_to(user.name, user) %></li>
			<% end %>
		</ul>

app/views/users/new.html.erb
 <% content_for(:title, "Sign up") %>
<h1>Sign up</h1><p>
<%= render 'form' %>
</p>

app/views/users/show.html.erb
<% content_for(:title, @user.name) %>
<article>
<header>
	<h1><%= @user.name %></h1><p>
  Member Since:
  <%= @user.created_at.strftime("%B %Y") %>
</p>
<p>
  <%= profile_image_for(@user) %>
	<header>
		<ul id="users">
      <li> <%=  mail_to(@user.email) %></li>
		</ul>
    <p>
      <ul>
      Check ins:
      <% @visited_places.each do |place| %>
      <li>
        <%= link_to place.name, place %>
      </li>
      <% end %>
    </ul>
    </p>
<% if @reviews.any? %>
<p>Recent Reviews:  <%= link_to("(View All)",  user_reviews_path) %> 
</p>
<ul>
<% @reviews.each do |review| %>
<li>
  <%= link_to review.place.name, review.place %>
  ( <%= time_ago_in_words(review.created_at) %> ago)

</li>
<% end %>
</ul>
<% end %>
	<footer>
  <nav>
    <% if current_user?(@user) %>
    <%= link_to 'Edit Account', edit_user_path(@user), class: 'btn default-btn' %>
    <%= link_to 'Delete Account', @user,
                method: :delete,
                data: { confirm: 'Are you sure you want to permanently delete your account?' },
                class: 'btn default-btn' %>
      <% end %>
  </nav>
</footer>
</article>

app/views/users/user_reviews.html.erb
<header>
<h1> <%= link_to current_user.name, current_user %>'s Reviews</h1>
</header>

<% current_user.reviews.each do |r| %>
<div style="margin:20px;">
	 <%= link_to r.place.name,r.place %> <%= link_to "Edit", edit_place_review_path(r.place,r) %><%= link_to "Delete", place_review_path(r.place, r), method: :delete, data: {confirm: 'Are you sure?'} %>
<div style="float:right;">
	<%= time_ago_in_words(r.created_at) %> ago<p> Meal Size: <%= r.meal_size %></p></div>
<p>
	<%= "#{r.comment}" %>
	<br/> Price Paid: <%= number_to_currency(r.price) %>
</p>
</div>
<% end %>