config/routes.rb
Rails.application.routes.draw do
  

 resources :cuisines


get "signin" => "sessions#new"
get "signup" => "users#new"

resource :session

resources :users
  root "places#index"

get "places/filter/:scope" => "places#index", as: :filter
get "user/reviews" => "users#user_reviews", as: :user_reviews
  resources :places do
    resources :reviews
    resources :check_ins
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
	
	validates :name, presence:true, uniqueness: true
	validates :description, length: {minimum: 25}
	validates :price, numericality: { greater_than_or_equal_to: 0}
	validates :rating, numericality: { only_integer: true, greater_than: 0}
	validates :image_file_name, allow_blank: true, format: { with: /\w+\.(git|jpg|png)\z/i,
		message: "must be a GIF, JPG, or PNG image"}
	validates :slug, uniqueness: true
	has_many :reviews, -> { order(created_at: :desc) }, dependent: :destroy
	has_many :check_ins, dependent: :destroy
	has_many :visitors, through: :check_ins, source: :user
	has_many :cuisines, through: :cuisinizations
	has_many :cuisinizations, dependent: :destroy
	
	before_validation :generate_slug

	scope :lowest_price, -> { order('price asc') }
	scope :highest_price, -> { order('average_price desc')}
	scope :largest_meal, -> { order('average_meal_size desc')}
	scope :location, ->(location="London") {where(location: location)}
	# scope :by_price, ->(price) {where.(price: price).sort_by_largest_meal}
	# scope :recent_reviews, -> where("review.created_at >= ?", Time.now).order(created_at: :desc).by_price }
	# :past_n_days, ->(days) { where('created_at >= ?' , days.days.ago) }
	def none?
		rating.blank? 
	end
	def average_meal_size
    reviews.average(:meal_size)
  end
	def average_price
    reviews.average(:price)
  end
  def to_param
  	slug
  end
  def generate_slug
  	self.slug ||= name.parameterize if name
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

before_action :require_signin, except: [:index, :show]
before_action :require_admin, except: [:index, :show]
before_action :set_place, only: [:show, :edit, :update,:destroy]
def index
		if params[:scope].in? %w(lowest_price highest_price largest_meal)
    @place = Place.send(params[:scope])
		else
		@places = Place.all
		end
	end
	def show
		
		@cuisines = @place.cuisines
		@visitors = @place.visitors
		if current_user
		@current_check_in = current_user.check_ins.find_by(place_id: @place.id)
		@current_review = current_user.reviews.find_by(place_id: @place.id)
		
	end
	end
	def edit
		
	end
	def update
		place_params
		if @place.update(place_params)
		redirect_to @place, notice: "Succesfully updated #{@place.name}"
	else 
		render :edit
	end
	end
	def new
		@place = Place.new
	end
	def create
		place_params
		@place = Place.new(place_params)
		if @place.save
		redirect_to @place, notice: "Succesfully created #{@place.name}"
	else
		render :new
	end
	end
	def destroy
		@place.destroy
		redirect_to places_url, notice: "Succesfully deleted #{@place.name}"
	end
end


private
def place_params 
	 params.require(:place).
	 permit(:name, :location, :description, :meal_size, :rating, :image_file_name, cuisine_ids: [])
end
def set_place
@place = Place.find_by!(slug: params[:id])
	end

app/helpers/places_helper.rb
module PlacesHelper

	def format_rating(place)
		if place.rating.blank?
			"No reviews"
		else
			place.rating
		end
	end
	def format_meal_size(place)
		if place.average_meal_size.blank?
			"No reported meal sizes"
		else
			place.average_meal_size
		end
	end
	def format_price(place)
		if place.average_price.blank?
			"No listed price"
		else
			number_to_currency(place.average_price)
		end
	end
	def image_for(place)
		if place.image_file_name.blank?
			image_tag 'placeholder.jpg'
		else
			image_tag(place.image_file_name)
		end
	end
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>

	<%= render 'shared/errors', object: @place %>

	<p>
		
		<%= f.label :name %>

		<%= f.text_field :name %>

	</p>
	<p> 
		<%= f.label :description %><br/>

		<%= f.text_area :description, cols:40, rows: 7 %>

	</p>
	<p>
		<%= f.label :location %></br>

		<%= f.text_field :location %>

	</p>

	<p>
		<%= f.label :price %></br>
		<%= f.number_field :price %>
	</p>
	<p><%= f.label :rating %><br/>
		<%= f.number_field :rating%>
	</p>
		</p>
		<p><%= f.label :image_file_name %><br/>
		<%= f.text_field :image_file_name %>
	</p>
		</p>
		
	<p>
		<%= f.collection_check_boxes(:cuisine_ids, Cuisine.all, :id, :name) %>
	</p>
	<p>
	<%= f.submit %>
	</p>
	<% end %>
	<p>
<%= link_to "All Restaurants","/places" %>
</p>

app/views/places/edit.html.erb
<h1>Editing <%= @place.name %></h1>
<%= render 'form' %>

app/views/places/index.html.erb
	 <% content_for(:title, "Feast Finder - Search") %>
	<h2><%= pluralize(@places.size,'Restaurant') %></h2>
	<% @places.each do |place| %>

	<h3><%= link_to(place.name, place) %></h3>
	<p><%= truncate(place.description, length:45) %></p>
		<div>
			<%= image_for(place) %>
		</div>
	<table class="table-responsive">
		<tr><th>Average Price Per Meal</th>
		<td><%= format_price(place) %></td>
		<tr>
			<th> Rating: </th>
			<td><%= format_rating(place) %></td>
		</tr>
		<tr>
			<th> Meal Size Rating: </th>
			<td>
				<%= format_meal_size(place) %>
			</td>
		</tr>
		<tr>
			<th> Location: </th>
			<td>
				<%= place.location %>
			</td>
		</tr>
	</table>
	<% end %>

app/views/places/new.html.erb
 <% content_for(:title, "Add a Restaurant") %>

<h1>Add Restaurant</h1>

<%= render 'form' %>
<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<% content_for(:title, @place.name) %>
		<%= image_for(@place) %>
<article>
	<header><h3><%= @place.name %></h3></header>
	<p>
		<% if current_user %>
		<% if @current_check_in %>
		<%= button_to "You've Checked in", place_check_in_path(@place, @current_check_in), method: :delete %>
		<% else %>
		<%= button_to "Check-in", place_check_ins_path(@place), class: "btn" %>
		<% end %>
		<% end %>
	</p>
	<p>
		<%= @place.description %></p>
	<table>
		<tr><th>Average Price Per Meal</th>
		<td><%= format_price(@place) %></td>
		<tr>
			<th> Rating: </th>
			<td><%= format_rating(@place) %></td>
		</tr>
		<tr>
			<th> Meal Size Rating: </th>
			<td>
				<%= format_meal_size(@place) %>
			</td>
		</tr>

		<tr>
			<th> Location: </th>
			<td>
				<%= @place.location %>
			</td>
		</tr>
		<tr>

		<tr>
			<th> Cuisine: </th>
			<td>
				<ul><% @cuisines.each do |cuisine| %><li><%= cuisine.name %></li> <% end %></ul>
			</td>
		</tr>
		<tr>
			
			<th> <%= pluralize(@visitors.size, 'Check in') %> </th>
			<td>
				<% if @visitors.any? %>
				
				<br/><ul>
				<% @visitors.each do |user| %>
				<li><%= link_to user.name, user %></li>
				<% end %>
			
			</ul>
				<% end %>
			</td>
		</tr>
	</table>
</article>
<%= link_to "Write a Review", new_place_review_path(@place) %>
 <%= link_to("Reviews", place_reviews_path(@place)) %>
<%= link_to "All Restaurants","/places" %>
<% if current_user_admin? %>
<%= link_to "Edit",edit_place_path(@place) %>
<%= link_to "Delete", place_path(@place), method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>
<% @place.reviews.each do |r| %>
<div style="margin:20px;">
	 by <%= link_to r.user.name,r.user %>
	 <% if r.user == current_user %> | <%= link_to "Edit", edit_place_review_path(r.place,r.user) %> | <%= link_to "Delete", place_review_path(r.place, r.user), method: :delete, data: {confirm: 'Are you sure?'} %>
	 <% else  %> 
	 <% end %>
<div style="float:right;">
	<%= time_ago_in_words(r.created_at) %> ago<p> Meal Size: <%= r.meal_size %></p></div>
<p>
	<%= "#{r.comment}" %>
	<br/> Price Paid: <%= number_to_currency(r.price) %>
</p>
</div>
<% end %>